### ISSUE TITLE
Non-reversible DCT

### ISSUE THREAD

**Issue by Smilebags** [nayuki/Nayuki-web-published-code#6]
Hi,

Thank you for implementing DCT in so many languages, it is incredibly helpful.

I'm using FastDCT.ts from `Nayuki-web-published-code/fast-discrete-cosine-transform-algorithms/FastDct.ts` and have noticed when using fastDctLee.transform followed by fastDctLee.inverseTransform on the same array, the result seems to be scaled up by a factor of 4. Codified:

```ts
let arr: number[] = [0,1,2,3,4,5,6,7];
fastDctLee.transform(arr);
console.log(arr); // [ 28, -12.884646045410275, 0, -1.3469096018078828, 0, -0.4018058074719937, 0, -0.10140464551929199 ]
fastDctLee.inverseTransform(arr);
console.log(arr); // [ -1.7763568394002505e-15, 4, 8, 12.000000000000004, 15.999999999999996, 20, 24, 28 ]
```

Is this a feature of fastDctLee, or am I right to expect applying the inverse transform should get me back to the original data? If this is how it is intended to work, what adjustment would I need to make to make it 'symmetrical'?

**Comment by Smilebags** [comment]
Alright so after some further reading I found this on the [DCT Wiki page](https://en.wikipedia.org/wiki/Discrete_cosine_transform#Inverse_transforms)

> The inverse of DCT-II is DCT-III multiplied by 2/N...

This means to write a symmetrical set of functions, I just need to multiply each element by 2/N after the inverse transform.

Since I would like to use a more functional approach, I will be refactoring the code in a couple of ways to:
* Align it more with TypeScript convention
* Add more thorough types
* Convert it into an ES6 module which can have members exported
* Modify the functions to return a new array rather than mutating the original

Because I'm making so many changes (and making it significantly differ from the other implementations), I assume you are probably not interested in merging a pull request with the changes but I wanted to make the offer.

**Comment by nayuki** [comment]
Hi, thanks for your compliments and investigative effort!

You are basically correct on all counts. Note that my code comments specifically say "Computes the unscaled DCT type II on the specified array in place.", so you did receive warning.

I am interested in seeing all the changes in your first 3 bullet points (in well-separated commits), but I can't guarantee I'll adopt them.

**Comment by nayuki** [comment]
I'm curious as to what you mean by aligning with TypeScript convention and adding more through types. I did the best I can and didn't intentionally omit anything, but I definitely have my share of blind spots as a beginner in TypeScript.
