### ISSUE TITLE
force-crc32

### ISSUE THREAD

**Issue by bucanero** [nayuki/Nayuki-web-published-code#9]
Not an issue (and probably off-topic), but...

Your web article and open-source implementation of the [force-crc32 solution](https://github.com/nayuki/Nayuki-web-published-code/blob/master/forcing-a-files-crc-to-any-value/forcecrc32.c) was great. Thank you for sharing it! 👍 
I actually had no idea that a non-brute-force approach was possible and was happily surprised when I found your article on the web.

Cheers! 👋

**Comment by nayuki** [comment]
Thanks for the compliments, glad you enjoyed my work!
